### ISSUE TITLE
Build fails on Mavericks with (libuv) Failed to create kqueue (24)

### ISSUE THREAD

**Issue by vielmetti** [kogmbh/WebODF#891]
OSX Mavericks 10.9.5, node v0.10.35. The error in the build process is

```
(libuv) Failed to create kqueue (24)

undefined:662
        console.log(err);
                ^
TypeError: Object #<Object> has no method 'log'
    at process.eval (eval at inner_run (/Users/emv/src/WebODF/webodf/lib/runtime.js:1840:51), <anonymous>:662:17)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:295:26)
```

This ends up being this problem:

https://github.com/joyent/node/issues/5658

which is solved in my case with running `ulimit -n 8192` before doing the build.

**Comment by vielmetti** [comment]
This also affects ViewerJS at https://github.com/kogmbh/ViewerJS/issues/142

**Comment by kossebau** [comment]
No OSX around myself to check. But seems a good find.
Sounds like `ulimit -n 8192` should be also mentioned in the build instructions?
