### ISSUE TITLE
Build issue on Fedora v31

### ISSUE THREAD

**Issue by ralphkw1** [kogmbh/WebODF#954]
I know this project is not being maintained. But in case someone is searching for a solution for the following problem:

```
-- Android was not found: APK will not be built.
uild/webodf/webodf/webodf/tools/updateJS.js
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:143:9)
    at Object.writeFile (fs.js:1251:14)
    at ReadFileContext.eval [as callback] (eval at inner_run (/home/rwilliamson/build/webodf/webodf/webodf/lib/runtime.js:1840:50), <anonymous>:546:20)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:256:13) {
  code: 'ERR_INVALID_CALLBACK'
}
undefined:674
        throw err;
        ^

```

Go to tool/updateJS.js and replace line 546 with the following to add the missing callback:

```
                fs.writeFile(lpath, contents,
					function(err, result) {
     					if(err) console.log( "runJSLint(), error:", err );
   					});

```

**Comment by zhivko** [comment]
Would you mind fixing this in source file? Or what is the reason not doing it this way and leave it to user to change code?
